Format comment

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -193,16 +193,41 @@ runs:
         ADD_COMMENT: ${{ inputs.add_comment }}
         OUTPUT_JSON: ${{ inputs.output_json }}
       run: |
-        if [ "$ADD_COMMENT" = "true" ]; then
-          echo "Info: Adding report comment"
-          COMMENT_BODY=$(cat "$OUTPUT_JSON" | jq -Rs .)
-            curl -L \
-              -X POST \
-              -H "Authorization: bearer $GH_TOKEN" \
-              -H "Content-Type: application/json" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              -d "{\"body\": $COMMENT_BODY}" \
-              "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"
-        else
+        if [ "$ADD_COMMENT" != "true" ]; then
           echo "Info: Skipping comment"
+          exit 0
         fi
+
+        if [ ! -f "$OUTPUT_JSON" ]; then
+          echo "Error: Output file not found: $OUTPUT_JSON"
+          exit 1
+        fi
+
+        # Extract basic fields
+        IMAGE_VERSION=$(jq -r '.imageVersion' "$OUTPUT_JSON")
+        IMAGE_NAME=$(jq -r '.imageName' "$OUTPUT_JSON")
+        SCAN_STATUS=$(jq -r '.scanStatus' "$OUTPUT_JSON")
+
+        # Count CVE's
+        TOTAL_CVES=$(jq '.introducedCves | length' "$OUTPUT_JSON")
+        NEW_CVES=$(jq '[.introducedCves[] | select(.status == "introduced")] | length' "$OUTPUT_JSON")
+        OLD_CVES=$(jq '[.introducedCves[] | select(.status == "no_change")] | length' "$OUTPUT_JSON")
+        HIGH_CVES=$(jq '[.introducedCves[] | select(.severity == "HIGH")] | length' "$OUTPUT_JSON")
+
+        COMMENT="## 🏄‍♂️ Upwind Image Scan Report
+        - **Image:** \`$IMAGE_NAME:$IMAGE_VERSION\`
+        - **Status:** \`$SCAN_STATUS\`
+        - **Total CVEs:** $TOTAL_CVES - ($NEW_CVES new and $OLD_CVES existing)
+        - **High Severity CVEs:** $HIGH_CVES
+
+        echo "Posting comment on PR:"
+        echo "$COMMENT"
+
+        COMMENT_JSON=$(jq -n --arg body "$COMMENT" '{ body: $body }')
+          curl -L \
+            -X POST \
+            -H "Authorization: bearer $GH_TOKEN" \
+            -H "Content-Type: application/json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d "$COMMENT_JSON" \
+            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"
